/* 27. Suppose consider we are working on Manufacturing company production house and we have
some machinery in production house can produce some product and we want develop the application
for following purpose 

1. Allocate machinery for production house 
2. Allocate products to machinery 
3. Count the total number of products produced by all machines 
4. Count the all products produced by single specific machine by using its id
5. View all products from production house 
6. View all products produced by particular machine 
For achieve about task we have following class structure 
1. Product class : it is POJO class with field id,name,rate,qty,count 
2. Machinery Class: it is also POJO class which accept Products and return products details it
contain following methods 
Machinery class contain field id, name, comp, capacity 
Note: machinery cannot accept product count more than its capacity of products 
void setProducts(Product p[]): this function can accept number of products for products 
Product [] getProducts(): this function can return total number product machinery class
int getTotalProductsCount(): this function can return total products count generated by machines  
Product getProductById(int id): this function can accept id of product generated by machine
and return product reference and if product not found return null

. ProductionHouse : this class can accept Machinery and machine class have some details
Machinery class contain field id, name, comp, capacity 
Note: machinery cannot accept product count more than its capacity of products 
ProductionHouse class contain following methods 
void allocateMachine(Machinery m[]): this method can accept multiple machinery
Machinery [] getMachinery(): this method can return all machineries with details 
Product [] getProductsByMachineryId(int id): this function can accept machinery id and return all
products produced by machine and if id not found return null
Machinery [] getAllProductionByAllMachine(): this method can return all machinery and its product
details 
. ManufacturingHub : this is the main method class and this class contain cases for perform
above operation

Allocate machinery for production house 

If we want to allocate machinery to production house before machine, we must have production house
so we required to create class for production house
If we want to allocate machine to ProductionHouse we required to create classes for machinery  */


import java.util.*;

public class ManufacturingHub_26
{
	public static void main(Stirng x[])
	{
		Scanner sc = new Scanner(System.in);
		productionHous ph = new ProductionHouse();
		
		Machinery[] machine = null;
		
		while(true)
		{
			System.out.println("\n=====MAUNFACTURING MENU =====");
			System.out.println("1. Allocate MAchinery");
			System.out.println("2. Allocate Machinery");
			System.out.println("3. Total productes to machines");
			System.out.println("4.Product count by machine id");
			System.out.println("5. view all Product by machine id");
			System.out.println("7. Exit");
			
			System.out.println("Enter choice: ");
			int ch = sc.nextInt();
			
			swith (ch)
			{
				case 1 :
				System.out.print("How many machines? ");
				
				machines = new Machinery[mcount];
				
				for(int i = 0; i<mcount; i++)
				{
					System.out.println("\nEnter machine "+(i+1)+" details");
					System.out.print("ID :");
					int mid = sc.nextInt();
					
					System.out.print("Name: ");
					String mname = sc.next();
					
					System.out.print("company:");
					String comp = sc.nextInt();
					
					System.out.print("Capacity:");
					int cap = sc.nextInt();
					
					machines[i]= new Machinery(mid,mname,comp,cap);
					
				}
				ph.allocateMachine(machines);
				break;
				
				case 2:
				System.out.print("Enter Machine ID:");
				int mid =  sc.nextInt();
				
				machinery targetMachine = null;
				
				for(Machinery m : machines)
				{
					if(m.getID()==mid)
					{
						targetMachine = m;
						break;
					}
				}
				if(targetMachine == null)
				{
					System.out.println("Machine not found!");
					break;
				}
				System.out.print("How many products to add?");
				
				Product[] plist = new Product[pcnt];
				
				for(int i=0; i<pcnt ; i++)
				{
					System.out.println("\nEnter product "+(i+1)+ "details:");
					
					System.out.print("ID:");
					int pid = sc.nextInt();
					
					System.out.print("Name :");
					String pname = sc.next();
					
					System.out.print("Rate");
					float rate = sc.nextFloat();
					
					System.out.print("Qty: ");
					int count = sc.nextInt();
					
					System.out.print("Count :"):
					int count = sc.nextINt();
					
					plist[i] = new Product(pid, pname, rate ,qty,count);
				}
				targetMachine.setProducts(plist);
				break;
				case 3:
				
				int total = 0;
				for(Machinery m = machines)
				{
					total +=m.getTotalProductsCount();
					
				}
				System.out.println("Total production by all machines:");
				
				case 4:
					System.out.print("Enter machine id:");
					
					int id = sc.nextInt();
					
					Machinery machine = null;
					for(Machinery  m : machines)
					{
						if (m.getId()==id)
							machine = m;
					}
					if(machine ! = null)
					{
						System.out.println("Total product produced: "+machine.getTotalProductsCount());
						
					}
					else
					{
						System.out.println("machine not found!");
					}
					break;
					
					case 5;
					System.out.println("\n--All PRODUCTS FROM ALL MACHINES ----------");
					For(Machinery m : machines)
					{
						Product[] prods = m.getProducts();
						if(probs == null) continue;
						
						System.out.println("\nMAchine: "+m.getName());
						for(Product p : probs)
						{
							System.out.println(p.getId()+" "+p.getname);
						}
					}
			}
		}
	}
}


